apiVersion: v2
name: amd-gpu
description: A Helm chart for deploying Kubernetes AMD GPU device plugin
type: application
home: https://github.com/RadeonOpenCompute/k8s-device-plugin
sources:
  - https://github.com/RadeonOpenCompute/k8s-device-plugin
icon: https://raw.githubusercontent.com/RadeonOpenCompute/k8s-device-plugin/master/helm/logo.png
maintainers:
  - name: Kenny Ho <Kenny.Ho@amd.com>
keywords:
  - kubernetes
  - cluster
  - hardware
  - gpu

kubeVersion: ">= 1.18.0"
version: 0.1.0
appVersion: "1.18.0"
